blank_issues_enabled: false
contact_links:
  - name: Question / Test Report
    url: https://github.com/johnvoipguy/WateefyElectronics/issues/new?template=question-test-report.yml
  - name: Bug Report
    url: https://github.com/johnvoipguy/WateefyElectronics/issues/new?template=bug-report.yml
  - name: Feature Request
    url: https://github.com/johnvoipguy/WateefyElectronics/issues/new?template=feature-request.yml
